name: BossCustomisation
main: fr.maliimaloo.bosscustomisation.BossCustomisation
version: 0.0.1
author: gizzmo
api-version: 1.13

depend: [OmegaAPI]

commands:
  coller:
    description: Colle un schematic à l'emplacement du joueur
    usage: /coller <schematic_name>